In [1]:
# Import numpy library
import numpy as np

In [2]:
# Define an array
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
arr.ndim # Check number of dimention

2

In [4]:
arr.shape # Check the size of array each diemention.

(3, 5)

In [8]:
arr.size # Total size of the array

15

In [9]:
arr.dtype # Data type

dtype('int32')

In [10]:
arr.itemsize # Check individual item size in bytes

4

In [11]:
arr.data

In [12]:
# Creating the array
CretAry = np.array([1, 2, 3])
print(CretAry)
CretAry.dtype

[1 2 3]


dtype('int32')

In [13]:
CretAry = np.array([1.6, 2.7, 3.3])
print(CretAry)
CretAry.dtype

[1.6 2.7 3.3]


dtype('float64')

In [14]:
CretAry = np.array([1, 'Jack', 3.3])
print(CretAry)
CretAry.dtype

['1' 'Jack' '3.3']


dtype('<U11')

In [15]:
CretAry = np.array([[1, 2, 3],[4, 6, 8]])
CretAry

array([[1, 2, 3],
       [4, 6, 8]])

In [16]:
CretAry = np.array([[1, 2, 3],[4, 6, 8]], dtype=complex)
CretAry

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 6.+0.j, 8.+0.j]])

In [17]:
CretAry = np.zeros((5,4))
CretAry

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
CretAry = np.ones((5,4))
CretAry

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# create matrix with random value
CretAry = np.empty((2,5))
CretAry

array([[6.95186305e-310, 2.02369289e-320, 2.66437674e-313,
        2.66099448e-313, 6.95186305e-310],
       [1.69759663e-313, 1.69759663e-313, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [20]:
# the perameter 5 is start point and 30 is end point point, last one 2 is the differance between two value 
CretAry = np.arange(5,30,2)
CretAry

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [21]:
# the perameter 5 and 30 is the bounded range, last one 6 is the number of value 
CretAry = np.linspace(5,30,6)
CretAry

array([ 5., 10., 15., 20., 25., 30.])

In [22]:
# Print 1d array
parr = np.arange(4)
print(parr)

[0 1 2 3]


In [23]:
# Print 2d array
parr = np.arange(20).reshape(4,5)
print(parr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [24]:
# Print 3d array
parr = np.arange(30).reshape(3,5,2)
parr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])