In [1]:
import numpy as np

In [2]:
a = np.array([20,34,46,5])
b = np.arange(4)+1

# Addition
add = a + b
print('Addition')
print(add)
# Subtraction
sub = a - b
print('Subtraction')
print(sub)

# Product
pro = a * b
print('Product')
print(pro)

# Division
div = a / b
print('Division')
print(div)

Addition
[21 36 49  9]
Subtraction
[19 32 43  1]
Product
[ 20  68 138  20]
Division
[20.         17.         15.33333333  1.25      ]


In [3]:
# Matrix Product
x = np.array([[24,56,17],[87, 23, 12]])
print(x.shape)
y = (np.arange(6)+1).reshape(3, 2)
print(y.shape)
mpro = x @ y
mpro

(2, 3)
(3, 2)


array([[277, 374],
       [216, 338]])

In [4]:
# Dot Product
x = np.array([[24,56,17],[87, 23, 12]])
print(x.shape)
y = (np.arange(6)+1).reshape(3, 2)
print(y.shape)
dpro = x.dot(y)
dpro

(2, 3)
(3, 2)


array([[277, 374],
       [216, 338]])

In [5]:
# Random number generator
rg = np.random.default_rng(1)
a = rg.random((2,3))
b = np.ones((2,3), dtype=int)
b *= 3
b

array([[3, 3, 3],
       [3, 3, 3]])

In [6]:
b +=a

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [7]:
c = a + b
c

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [8]:
d = np.exp(c * 1J)
d

array([[-0.93224452-0.3618289j , -0.69031568-0.7235083j ,
        -0.99999671-0.00256696j],
       [-0.69162717-0.7222547j , -0.98554434-0.1694177j ,
        -0.96057485-0.27802151j]])

In [9]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print('Summation')
print(arr.sum())
print('Minimum')
print(arr.min())
print('Maximum')
print(arr.max())

Summation
21
Minimum
1
Maximum
6


In [10]:
rg = np.random.default_rng(1)
a = rg.random((2,3))
# Add in column
a.sum(axis=0)

array([1.46047107, 1.26229515, 0.56748606])

In [11]:
a.min(axis=1)

array([0.14415961, 0.31183145])