In [1]:
import numpy as np

In [4]:
a1 = np.arange(10,20,3)
a1

array([10, 13, 16, 19])

In [5]:
a2 = np.array([[1,2,3],[23,4,5]])
a2

array([[ 1,  2,  3],
       [23,  4,  5]])

In [6]:
a3 = a2.copy()
a3

array([[ 1,  2,  3],
       [23,  4,  5]])

In [7]:
a4 = np.empty([3,2])
a4

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
a5 = np.empty_like(a3)
a5

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
a6 = np.eye(3)
a6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
a7 = np.fromfunction(lambda qq,tt: qq+tt, (3,3), dtype=int)
a7

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [10]:
a8 = np.identity(3)
a8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
a9 = np.linspace(2.0,3.0,num=6)
a9

array([2. , 2.2, 2.4, 2.6, 2.8, 3. ])

In [12]:
a10 = np.logspace(1,10,6)
a10

array([1.00000000e+01, 6.30957344e+02, 3.98107171e+04, 2.51188643e+06,
       1.58489319e+08, 1.00000000e+10])

In [13]:
np.r_[np.array([1,2,3]),0,0,np.array([4,5,6])]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [14]:
np.r_[-1:1:6j, [2]*3, 5,6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  2. ,  2. ,  2. ,  5. ,  6. ])

In [15]:
# Concatinate the array
a11 = np.r_['-1', np.array([[1,2,3],[2, 3, 4]]), np.array([[1,2,3],[8, 3, 8]])]

### Conversion

In [16]:
a11.astype(float)

array([[1., 2., 3., 1., 2., 3.],
       [2., 3., 4., 8., 3., 8.]])

In [17]:
arr = np.array([1, 2, 3, 4])

In [18]:
np.atleast_1d(arr)

array([1, 2, 3, 4])

In [19]:
np.atleast_2d(arr)

array([[1, 2, 3, 4]])

In [20]:
np.atleast_3d(arr)

array([[[1],
        [2],
        [3],
        [4]]])

In [21]:
np.asmatrix(arr)

matrix([[1, 2, 3, 4]])