In [5]:
import numpy as np

### Array Split

In [6]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
np.array_split(arr, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

### Stack

In [8]:
a = np.array((1,2,3))
b = np.array((2,4,6))
np.column_stack((a,b))

array([[1, 2],
       [2, 4],
       [3, 6]])

In [9]:
np.dstack((a,b))

array([[[1, 2],
        [2, 4],
        [3, 6]]])

In [10]:
np.hstack((a,b))

array([1, 2, 3, 2, 4, 6])

In [11]:
np.vstack((a,b))

array([[1, 2, 3],
       [2, 4, 6]])

### Concatenate

In [12]:
# axis = 0 fot horzontal, 1 for vertical or None
a = np.array([[1,2,3],[5,6,7]])
b = np.array([[3,6,7]])
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [5, 6, 7],
       [3, 6, 7]])

### Diagonal

In [13]:
dig = np.arange(16).reshape(4,4)
print(dig)
print()
print(dig.diagonal())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[ 0  5 10 15]


In [14]:
dig.diagonal(1)

array([ 1,  6, 11])

### Filp left to right or up to down

In [26]:
np.fliplr(dig)

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [27]:
np.flipud(dig)

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

### Split

In [15]:
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
np.dsplit(arr,2)

[array([[[ 0,  1],
         [ 4,  5],
         [ 8,  9]],
 
        [[12, 13],
         [16, 17],
         [20, 21]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]],
 
        [[14, 15],
         [18, 19],
         [22, 23]]])]

In [99]:
arr = np.arange(24).reshape(4,6)
np.hsplit(arr,2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [100]:
np.vsplit(arr,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

Add new axis and ravel

In [76]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(arr)

array([1, 2, 3, 4, 5, 6])

In [77]:
x = np.ravel(arr,order='F')

In [78]:
x[:, np.newaxis]

array([[1],
       [4],
       [2],
       [5],
       [3],
       [6]])

### Repeat

In [79]:
np.repeat(3,4)

array([3, 3, 3, 3])

In [16]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
np.repeat(x,2)

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9,  9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15])

In [86]:
np.repeat(x, 2, axis=1)

array([[ 0,  0,  1,  1,  2,  2,  3,  3],
       [ 4,  4,  5,  5,  6,  6,  7,  7],
       [ 8,  8,  9,  9, 10, 10, 11, 11],
       [12, 12, 13, 13, 14, 14, 15, 15]])

In [94]:
np.repeat(x, [1, 2, 3, 1], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Resize

In [96]:
a = np.arange(8)
np.resize(a,(4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [97]:
np.resize(a,(2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### Transpose

In [19]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
np.transpose(arr)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [21]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])