In [1]:
import numpy as np

### All

In [26]:
arr = np.array([[True, True],[False, True]])
arr

array([[ True,  True],
       [False,  True]])

In [28]:
np.all(arr)

False

In [6]:
arr = np.array([[True, True],[True, True]])
np.all(arr)

True

In [7]:
arr = np.array([[True, True],[False, True]])
np.all(arr, axis=0)

array([False,  True])

### Any

In [9]:
arr = np.array([[True, True],[False, True]])
np.any(arr)

True

In [10]:
arr = np.array([[True, True],[True, True]])
np.any(arr)

True

In [11]:
arr = np.array([[True, False],[True, False]])
np.any(arr)

True

In [13]:
arr = np.array([[False, False],[False, False]])
np.any(arr)

False

In [16]:
arr = np.array([[True, False],[True, False]])
np.any(arr, axis=0)

array([ True, False])

In [17]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
x

array([[3, 0, 0],
       [0, 4, 0],
       [5, 6, 0]])

### nonzero

In [18]:
np.nonzero(x)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

### where

In [21]:
a = np.arange(10)


Where use as,
if x > 5:
return a
else:
return a*10

In [25]:
np.where(a > 5, a, a*10)

array([ 0, 10, 20, 30, 40, 50,  6,  7,  8,  9])