In [2]:
import numpy as np

In [15]:
arr = np.arange(12).reshape(3,4)
arr[0,1] = 77
arr[0,0] = 11
arr[1,3] = 0
arr

array([[11, 77,  2,  3],
       [ 4,  5,  6,  0],
       [ 8,  9, 10, 11]])

In [16]:
np.argmax(arr)

1

In [17]:
np.argmax(arr, axis=0)

array([0, 0, 2, 2], dtype=int64)

In [18]:
np.argmax(arr, axis=1)

array([1, 2, 3], dtype=int64)

In [19]:
np.argmin(arr)

7

In [20]:
np.argmin(arr, axis=0)

array([1, 1, 0, 1], dtype=int64)

In [21]:
np.argmin(arr, axis=1)

array([2, 3, 0], dtype=int64)

In [22]:
arr = np.array([2,6,4,1,0,6,8,3])
arr

array([2, 6, 4, 1, 0, 6, 8, 3])

In [23]:
np.argsort(arr, kind="mergesort")

array([4, 3, 0, 7, 2, 1, 5, 6], dtype=int64)

In [26]:
np.max(arr)

8

In [27]:
np.min(arr)

0

In [28]:
np.sort(arr)

array([0, 1, 2, 3, 4, 6, 6, 8])

In [30]:
#ptp mean peak to peak (Maximum - Minimum)
arr = np.array([[2,6,9],[5,9,7]])
arr

array([[2, 6, 9],
       [5, 9, 7]])

In [31]:
np.ptp(arr, axis=0)

array([3, 3, 2])

In [32]:
np.ptp(arr, axis=1)

array([7, 4])

In [33]:
arr = np.array([9,0,3,6,1,90,37,32,73])
arr

array([ 9,  0,  3,  6,  1, 90, 37, 32, 73])

In [34]:
# This function does sort first, then find the expected value
np.searchsorted(arr,90)

9