In [4]:
import numpy as np

In [5]:
arr = np.array([[6,8,2,9],[45,3,5,2],[5,7,8,2]])
arr

array([[ 6,  8,  2,  9],
       [45,  3,  5,  2],
       [ 5,  7,  8,  2]])

In [6]:
np.choose([1,2,0,0],arr)

array([45,  7,  2,  9])

In [7]:
a = np.array([[1, 2, 5], [3, 4, 34], [5, 6, 12]])
a

array([[ 1,  2,  5],
       [ 3,  4, 34],
       [ 5,  6, 12]])

In [8]:
np.compress([0,1],a, axis=0)

array([[ 3,  4, 34]])

In [9]:
# Cumulative product
arr = np.array([1,2,4])
np.cumprod(arr)

array([1, 2, 8], dtype=int32)

In [10]:
arr = np.array([[1,2,3],[4,2,5]])
np.cumprod(arr, axis=0)

array([[ 1,  2,  3],
       [ 4,  4, 15]], dtype=int32)

In [11]:
np.cumprod(arr, axis=1)

array([[ 1,  2,  6],
       [ 4,  8, 40]], dtype=int32)

In [12]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 12, 17], dtype=int32)

In [13]:
np.cumsum(arr, axis=0)

array([[1, 2, 3],
       [5, 4, 8]], dtype=int32)

In [14]:
np.cumsum(arr, axis=1)

array([[ 1,  3,  6],
       [ 4,  6, 11]], dtype=int32)

In [15]:
# It works as: (1*0)+(2*2)+(3*2) = 10
a = np.array([1,2,3])
b = np.array([0,2,2])
np.inner(a,b)

10

In [16]:
a = np.arange(12).reshape((3,4))
b = np.arange(4)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]


In [17]:
np.inner(a,b)

array([14, 38, 62])

In [18]:
# Fill
a.fill(1)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
a = np.array([1+2j, 3+5j, 8+2j])
a

array([1.+2.j, 3.+5.j, 8.+2.j])

In [20]:
np.imag(a)

array([2., 5., 2.])

In [21]:
a.imag = np.array([10,12,15])
a

array([1.+10.j, 3.+12.j, 8.+15.j])

In [22]:
np.real(a)

array([1., 3., 8.])

In [23]:
a.real = np.array([10,30,80])
a

array([10.+10.j, 30.+12.j, 80.+15.j])

In [24]:
a = ((np.arange(6))+1).reshape((2,3))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.prod(a)

720

In [26]:
np.prod(a, axis=0)

array([ 4, 10, 18])

In [27]:
np.prod(a, axis=1)

array([  6, 120])

In [28]:
np.put(a, [0,4],[23,-56])
a

array([[ 23,   2,   3],
       [  4, -56,   6]])

In [29]:
np.putmask(a, a > 10, 1)
a

array([[  1,   2,   3],
       [  4, -56,   6]])

In [30]:
a.sum()

-40

In [31]:
np.sum(a, axis=0)

array([  5, -54,   9])

In [32]:
np.sum(a, axis=1)

array([  6, -46])