In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4,5,6])
np.cross(a,b)

array([-3,  6, -3])

In [3]:
x = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
y = np.array([[7, 8, 9], [4,5,6], [1,2,3]])
np.cross(x,y)

array([[ -6,  12,  -6],
       [  0,   0,   0],
       [  6, -12,   6]])

In [4]:
np.cross(x, y, axisa=0, axisb=0)

array([[-24,  48, -24],
       [-30,  60, -30],
       [-36,  72, -36]])

In [5]:
np.dot(x,y)

array([[ 18,  24,  30],
       [ 54,  69,  84],
       [ 90, 114, 138]])

In [7]:
np.outer(x,y)

array([[ 7,  8,  9,  4,  5,  6,  1,  2,  3],
       [14, 16, 18,  8, 10, 12,  2,  4,  6],
       [21, 24, 27, 12, 15, 18,  3,  6,  9],
       [28, 32, 36, 16, 20, 24,  4,  8, 12],
       [35, 40, 45, 20, 25, 30,  5, 10, 15],
       [42, 48, 54, 24, 30, 36,  6, 12, 18],
       [49, 56, 63, 28, 35, 42,  7, 14, 21],
       [56, 64, 72, 32, 40, 48,  8, 16, 24],
       [63, 72, 81, 36, 45, 54,  9, 18, 27]])

In [8]:
a = np.random.randn(9, 6) + 1j*np.random.randn(9, 6)
b = np.random.randn(2, 7, 8, 3) + 1j*np.random.randn(2, 7, 8, 3)

In [15]:
u, s, vh = np.linalg.svd(a, full_matrices= True)
u.shape, s.shape, vh.shape

((9, 9), (6,), (6, 6))

In [17]:
a = np.array([[1, 4], [5, 6]])
b = np.array([[4, 1], [2, 2]])
np.vdot(a, b)

30