In [2]:
import numpy as np
from io import StringIO

Split the line into column

In [14]:
data = '1,2,3,4,5,6'
np.genfromtxt(StringIO(data), delimiter=",")

array([1., 2., 3., 4., 5., 6.])

In [15]:
data = u'1,2,3\n4,5,6'
np.genfromtxt(StringIO(data), delimiter=",")

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
data = u'1 2 3\n 5 8 9'
np.genfromtxt(StringIO(data), delimiter=None)

array([[1., 2., 3.],
       [5., 8., 9.]])

In [22]:
data = u'121314\n151617'
np.genfromtxt(StringIO(data), delimiter=2)

array([[12.,  1.,  3., 14.],
       [ 1., 51., 61.,  7.]])

The autostrip argument

In [24]:
data = u'1, jack , 2\n 3, Nayem , 45'
np.genfromtxt(StringIO(data), delimiter=',', dtype='|U5') # focuse on space

array([['1', ' jack', ' 2'],
       ['3', ' Naye', ' 45']], dtype='<U5')

In [26]:
data = u'1, jack , 2\n 3, Nayem , 45'
np.genfromtxt(StringIO(data), delimiter=',', dtype='|U5', autostrip=True) # focuse on space

array([['1', 'jack', '2'],
       ['3', 'Nayem', '45']], dtype='<U5')

In [29]:
data = u'''#
# Skip me
# Also skip me
1,2
5,6
7,4
3,7 # This line skiping again
'''
np.genfromtxt(StringIO(data), comments='#', delimiter=',')

array([[1., 2.],
       [5., 6.],
       [7., 4.],
       [3., 7.]])

The skip_header and skip_footer arguments

In [31]:
data = u'\n'.join(str(i) for i in range(10))
np.genfromtxt(StringIO(data), skip_header=1, skip_footer=5)

array([1., 2., 3., 4.])

The usecols argument

In [37]:
data = u'1 2 3\n 4 7 9'
np.genfromtxt(StringIO(data), usecols=(0, 1))

array([[1., 2.],
       [4., 7.]])

In [38]:
data = u'1 2 3\n 9 0 5'
np.genfromtxt(StringIO(data), names="a, b, c", usecols=('a, c'))

array([(1., 3.), (9., 5.)], dtype=[('a', '<f8'), ('c', '<f8')])

Setting the names

In [39]:
data = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(data, dtype=[(_, int) for _ in 'abc'])

array([(1, 2, 3), (4, 5, 6)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<i4')])

In [41]:
data = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(data, names="A, B, C")

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])

In [43]:
data = StringIO("a b c\n 1 2 3\n 4 5 6")
np.genfromtxt(data, names=True)

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [44]:
data = StringIO("1 2 3\n 4 5 6")
ndtype = [('a', int), ('b',float), ('c', int)]
names = ['A', 'B', 'C']
np.genfromtxt(data, names=names, dtype = ndtype)

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('A', '<i4'), ('B', '<f8'), ('C', '<i4')])

The defaultfmt argument

In [51]:
data = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(data, dtype=(int, float, float), defaultfmt='jac%02i')

array([(1, 2., 3.), (4, 5., 6.)],
      dtype=[('jac00', '<i4'), ('jac01', '<f8'), ('jac02', '<f8')])

Missing value

In [63]:
data = u'N/A, 2, 4\n4, ,???'
np.genfromtxt(StringIO(data),
              dtype=int,
              delimiter=',',
              names='i, j, k',
              missing_values={0:"N/A", 'b':" ", 2:"???"},
              filling_values={0:0, 'b':0, 2:99}
             )

array([(0,  2,  4), (4, -1, 99)],
      dtype=[('i', '<i4'), ('j', '<i4'), ('k', '<i4')])