In [1]:
import numpy as np

In [2]:
myarr = np.array([1, 0, np.nan, 3])

In [7]:
np.nonzero(myarr == np.nan)

(array([], dtype=int64),)

In [8]:
np.nan == np.nan

False

In [9]:
myarr[myarr == np.nan] =0
myarr

array([ 1.,  0., nan,  3.])

In [12]:
myarr[np.isnan(myarr)] = 11

In [13]:
myarr

array([ 1.,  0., 11.,  3.])

In [23]:
x = np.arange(12.)
x[3:6] = np.nan
x

array([ 0.,  1.,  2., nan, nan, nan,  6.,  7.,  8.,  9., 10., 11.])

In [24]:
x.sum()

nan

In [25]:
np.nansum(x)

54.0

In [26]:
np.nanmax(x)

11.0

In [27]:
np.nanmin(x)

0.0

In [28]:
np.nanargmax(x)

11

In [29]:
np.nanargmin(x)

0

In [34]:
olddetting = np.seterr(all='warn')
np.zeros(5,dtype=np.float32)/0.

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, nan, nan, nan, nan], dtype=float32)

In [35]:
j = np.seterr(under='ignore')
np.array([1.e-100])**10

array([0.])

In [36]:
j = np.seterr(invalid='raise')
np.sqrt(np.array([-1.]))

FloatingPointError: invalid value encountered in sqrt

In [37]:
j = np.seterr(all='call')
np.zeros(5, dtype=np.int32)/0

NameError: python callback specified for invalid value (in  true_divide) but no function found.