In [1]:
import numpy as np

In [2]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [7]:
a = a.reshape(3,5)
a

array([[11, 11, 12, 13, 14],
       [15, 16, 17, 12, 13],
       [11, 14, 18, 19, 20]])

In [6]:
a.transpose()

array([[11, 15, 11],
       [11, 16, 14],
       [12, 17, 18],
       [13, 12, 19],
       [14, 13, 20]])

In [8]:
a.T

array([[11, 15, 11],
       [11, 16, 14],
       [12, 17, 18],
       [13, 12, 19],
       [14, 13, 20]])